[package]
name = "pomo-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.4.4"
log = "0.4.17"
simple_logger = "4.0.0"
relm4-macros = "0.4.4"
playback-rs = "0.2.5"
