[package]
name = "pomo-oxide"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
relm4 = "0.4.4"
gtk = { version = "0.4", package = "gtk4" }
